apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: vertx-istio-circuit-breaker-name-destination-initial
spec:
  destination:
    name: vertx-istio-circuit-breaker-name
    labels:
      app: vertx-istio-circuit-breaker-name
  circuitBreaker:
    simpleCb:
      maxConnections: 100
      httpMaxPendingRequests: 10
